In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('concrete_data.csv')
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
df.shape

(1030, 9)

In [4]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
concrete_data_columns = df.columns
predictors = df[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = df['Strength'] # Strength column

In [7]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [8]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [9]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [10]:
n_cols = predictors_norm.shape[1] # number of predictors

In [11]:
import keras

WARNING:tensorflow:From C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

In [16]:
# build the model
model = regression_model()

WARNING:tensorflow:From C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [17]:
# fit the model
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=2)

Epoch 1/50
WARNING:tensorflow:From C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

23/23 - 1s - loss: 1556.4504 - 502ms/epoch - 22ms/step
Epoch 2/50
23/23 - 0s - loss: 1541.4745 - 24ms/epoch - 1ms/step
Epoch 3/50
23/23 - 0s - loss: 1526.4067 - 21ms/epoch - 909us/step
Epoch 4/50
23/23 - 0s - loss: 1511.0693 - 35ms/epoch - 2ms/step
Epoch 5/50
23/23 - 0s - loss: 1495.1317 - 14ms/epoch - 607us/step
Epoch 6/50
23/23 - 0s - loss: 1478.3759 - 42ms/epoch - 2ms/step
Epoch 7/50
23/23 - 0s - loss: 1460.7714 - 62ms/epoch - 3ms/step
Epoch 8/50
23/23 - 0s - loss: 1441.5879 - 21ms/epoch - 896us/step
Epoch 9/50
23/23 - 0s - loss: 1420.9900 - 35ms/epoch - 2ms/step
Epoch 10/50
23/23 - 0s - loss: 1398.7289 - 21ms/epoch - 904us/step
Epoch 11/50
23/23 - 0s - loss: 1374.8250 - 27ms/epoch - 1ms/step
Epoch 12/50
23/23 - 0s - loss: 1349.3743 - 9ms/epoch - 402us/step
Epoch 13/50
23/23 - 0s - loss: 1321.8922 - 36ms/epoch - 2ms/step
Epoch 14/50
23/23 - 0s - loss: 1293.4277 - 23ms/epoch - 980us/step
Epoch 15/50
23/23 - 0s - loss: 1263.5205 - 11ms/epoch - 464us/step
Epoch 16/50
23/23 - 0s - loss: 1231.9573 - 21ms/epoch - 898us/step
Epoch 17/50
23/23 - 0s - loss: 1199.3743 - 22ms/epoch - 966us/step
Epoch 18/50
23/23 - 0s - loss: 1165.7026 - 29ms/epoch - 1ms/step
Epoch 19/50
23/23 - 0s - loss: 1131.3322 - 12ms/epoch - 522us/step
Epoch 20/50
23/23 - 0s - loss: 1095.1012 - 34ms/epoch - 1ms/step
Epoch 21/50
23/23 - 0s - loss: 1058.4735 - 7ms/epoch - 292us/step
Epoch 22/50
23/23 - 0s - loss: 1021.9173 - 13ms/epoch - 560us/step
Epoch 23/50
23/23 - 0s - loss: 984.4744 - 15ms/epoch - 674us/step
Epoch 24/50
23/23 - 0s - loss: 946.8295 - 22ms/epoch - 947us/step
Epoch 25/50
23/23 - 0s - loss: 909.5961 - 21ms/epoch - 915us/step
Epoch 26/50
23/23 - 0s - loss: 871.9105 - 18ms/epoch - 796us/step
Epoch 27/50
23/23 - 0s - loss: 835.3859 - 12ms/epoch - 527us/step
Epoch 28/50
23/23 - 0s - loss: 798.2087 - 10ms/epoch - 423us/step
Epoch 29/50
23/23 - 0s - loss: 761.9702 - 36ms/epoch - 2ms/step
Epoch 30/50
23/23 - 0s - loss: 726.7051 - 14ms/epoch - 626us/step
Epoch 31/50
23/23 - 0s - loss: 691.6428 - 9ms/epoch - 407us/step
Epoch 32/50
23/23 - 0s - loss: 658.3308 - 21ms/epoch - 906us/step
Epoch 33/50
23/23 - 0s - loss: 625.6181 - 24ms/epoch - 1ms/step
Epoch 34/50
23/23 - 0s - loss: 594.1411 - 21ms/epoch - 904us/step
Epoch 35/50
23/23 - 0s - loss: 564.0199 - 21ms/epoch - 907us/step
Epoch 36/50
23/23 - 0s - loss: 535.4376 - 35ms/epoch - 2ms/step
Epoch 37/50
23/23 - 0s - loss: 507.7606 - 21ms/epoch - 906us/step
Epoch 38/50
23/23 - 0s - loss: 482.1086 - 31ms/epoch - 1ms/step
Epoch 39/50
23/23 - 0s - loss: 457.6198 - 21ms/epoch - 901us/step
Epoch 40/50
23/23 - 0s - loss: 434.6923 - 21ms/epoch - 910us/step
Epoch 41/50
23/23 - 0s - loss: 413.3902 - 28ms/epoch - 1ms/step
Epoch 42/50
23/23 - 0s - loss: 393.4749 - 21ms/epoch - 907us/step
Epoch 43/50
23/23 - 0s - loss: 374.7952 - 29ms/epoch - 1ms/step
Epoch 44/50
23/23 - 0s - loss: 357.5650 - 28ms/epoch - 1ms/step
Epoch 45/50
23/23 - 0s - loss: 341.9960 - 14ms/epoch - 607us/step
Epoch 46/50
23/23 - 0s - loss: 327.1536 - 32ms/epoch - 1ms/step
Epoch 47/50
23/23 - 0s - loss: 313.9024 - 17ms/epoch - 742us/step
Epoch 48/50
23/23 - 0s - loss: 301.4751 - 28ms/epoch - 1ms/step
Epoch 49/50
23/23 - 0s - loss: 290.4062 - 28ms/epoch - 1ms/step
Epoch 50/50
23/23 - 0s - loss: 280.2199 - 29ms/epoch - 1ms/step

In [18]:
loss_val = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)
loss_val

10/10 [==============================] - 0s 1ms/step - loss: 268.5368
10/10 [==============================] - 0s 1ms/step

268.5368347167969

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

268.53683371570133 0.0

In [21]:
total_mean_squared_errors = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors with normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 112.23583984375
10/10 [==============================] - 0s 763us/step
MSE 2: 90.28465270996094
10/10 [==============================] - 0s 1ms/step
MSE 3: 58.578372955322266
10/10 [==============================] - 0s 2ms/step
MSE 4: 44.98436737060547
10/10 [==============================] - 0s 1ms/step
MSE 5: 42.70531463623047
10/10 [==============================] - 0s 2ms/step
MSE 6: 44.8945198059082
10/10 [==============================] - 0s 1ms/step
MSE 7: 45.11322021484375
10/10 [==============================] - 0s 2ms/step
MSE 8: 34.609676361083984
10/10 [==============================] - 0s 810us/step
MSE 9: 37.2086181640625
10/10 [==============================] - 0s 1ms/step
MSE 10: 36.32877731323242
10/10 [==============================] - 0s 934us/step
MSE 11: 36.844627380371094
10/10 [==============================] - 0s 0s/step
MSE 12: 33.63144302368164
10/10 [==============================] - 0s 0s/step
MSE 13: 40.94287109375
10/10 [==============================] - 0s 0s/step
MSE 14: 41.100975036621094
10/10 [==============================] - 0s 0s/step
MSE 15: 34.40359878540039
10/10 [==============================] - 0s 0s/step
MSE 16: 31.702402114868164
10/10 [==============================] - 0s 2ms/step
MSE 17: 37.16036605834961
10/10 [==============================] - 0s 2ms/step
MSE 18: 36.04676818847656
10/10 [==============================] - 0s 0s/step
MSE 19: 35.332916259765625
10/10 [==============================] - 0s 2ms/step
MSE 20: 34.651119232177734
10/10 [==============================] - 0s 3ms/step
MSE 21: 33.28338623046875
10/10 [==============================] - 0s 2ms/step
MSE 22: 34.73789596557617
10/10 [==============================] - 0s 2ms/step
MSE 23: 31.14086151123047
10/10 [==============================] - 0s 0s/step
MSE 24: 32.77182388305664
10/10 [==============================] - 0s 2ms/step
MSE 25: 36.739139556884766
10/10 [==============================] - 0s 2ms/step
MSE 26: 35.82575988769531
10/10 [==============================] - 0s 2ms/step
MSE 27: 32.904136657714844
10/10 [==============================] - 0s 1ms/step
MSE 28: 32.653106689453125
10/10 [==============================] - 0s 768us/step
MSE 29: 38.96755599975586
10/10 [==============================] - 0s 2ms/step
MSE 30: 36.21853256225586
10/10 [==============================] - 0s 778us/step
MSE 31: 31.209970474243164
10/10 [==============================] - 0s 2ms/step
MSE 32: 33.047054290771484
10/10 [==============================] - 0s 1ms/step
MSE 33: 32.63483810424805
10/10 [==============================] - 0s 1ms/step
MSE 34: 35.759422302246094
10/10 [==============================] - 0s 2ms/step
MSE 35: 34.62733840942383
10/10 [==============================] - 0s 0s/step
MSE 36: 41.543121337890625
10/10 [==============================] - 0s 2ms/step
MSE 37: 30.287960052490234
10/10 [==============================] - 0s 2ms/step
MSE 38: 37.58086013793945
10/10 [==============================] - 0s 2ms/step
MSE 39: 35.110618591308594
10/10 [==============================] - 0s 2ms/step
MSE 40: 30.37362289428711
10/10 [==============================] - 0s 1ms/step
MSE 41: 37.5998420715332
10/10 [==============================] - 0s 1ms/step
MSE 42: 29.729324340820312
10/10 [==============================] - 0s 922us/step
MSE 43: 35.707820892333984
10/10 [==============================] - 0s 2ms/step
MSE 44: 38.25639343261719
10/10 [==============================] - 0s 2ms/step
MSE 45: 37.048133850097656
10/10 [==============================] - 0s 1ms/step
MSE 46: 37.8924446105957
10/10 [==============================] - 0s 1ms/step
MSE 47: 33.975093841552734
10/10 [==============================] - 0s 2ms/step
MSE 48: 36.40543746948242
10/10 [==============================] - 0s 2ms/step
MSE 49: 36.383949279785156
10/10 [==============================] - 0s 2ms/step
MSE 50: 38.720367431640625
10/10 [==============================] - 0s 2ms/step


Below is the mean and standard deviation of 50 mean squared errors with normalized data. Total number of epochs for each training is: 100

Mean: 39.15792433811241
Standard Deviation: 13.727811574664223